FROM continuumio/miniconda3

# RUN conda install -y tensorflow-gpu
RUN mkdir -p /ml
WORKDIR /ml
COPY config/mldevenv.yaml /ml/mldevenv.yaml
# RUN conda env create --file mldevenv.yaml


# ENV NVIDIA_VISIBLE_DEVICES all
# ENV NVIDIA_DRIVER_CAPABILITIES utility,compute
CMD ["/bin/bash"]