FROM python:3.7-buster
COPY config/requirements.txt /
COPY .env /.env

RUN apt update \
  && apt-get install -y libopencv-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
RUN pip3 install -r requirements.txt